# Generated by Django 4.0.5 on 2022-06-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('red', '빨간색'), ('orange', '주황색'), ('yellow', '노란색'), ('green', '초록색'), ('blue', '파란색'), ('indigo', '남색'), ('purple', '보라색'), ('white', '하얀색'), ('black', '검은색'), ('other', '기타')], max_length=10, verbose_name='색깔')),
                ('height', models.CharField(choices=[('low', '로우'), ('middle', '미드'), ('high', '하이')], max_length=10, verbose_name='높이')),
                ('image', models.ImageField(upload_to='static/', verbose_name='신발 이미지')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.brand', verbose_name='브랜드')),
            ],
        ),
    ]
