# Generated by Django 4.0.5 on 2022-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='exposure_end',
            field=models.DateTimeField(default='2022-07-29 00:00:00', verbose_name='노출 종료'),
        ),
        migrations.AlterField(
            model_name='history',
            name='exposure_start',
            field=models.DateTimeField(default='2022-06-29 00:00:00', verbose_name='노출 시작일'),
        ),
    ]
