# Generated by Django 4.0.5 on 2022-06-30 02:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('history', '0002_alter_history_exposure_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='exposure_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 0, 0), verbose_name='노출 종료'),
        ),
        migrations.AlterField(
            model_name='history',
            name='exposure_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 0, 0), verbose_name='노출 시작일'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.image', verbose_name='사용된 이미지'),
        ),
    ]
