# Generated by Django 4.0.5 on 2022-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(max_length=150, upload_to='img/upload_img/%Y%m%d', verbose_name='첫번째 이미지')),
                ('image_two', models.ImageField(max_length=150, upload_to='img/upload_img/%Y%m%d', verbose_name='두번째 이미지')),
                ('image_result', models.ImageField(max_length=150, upload_to='img/upload_img/%Y%m%d', verbose_name='결과 이미지')),
            ],
        ),
    ]
